### ISSUE TITLE
scrobbling stopped working

### ISSUE THREAD

**Issue by dedeweb** [jellyfin/jellyfin-plugin-simkl#20]
The last time I watched a movie, scrobble didn't work. There is an error in logs : 

`[2022-08-25 20:42:07.049 +01:00] [ERR] Caught unknown exception while trying to scrobble
System.Text.Json.JsonException: The JSON value could not be converted to Jellyfin.Plugin.Simkl.API.Responses.SearchFileResponse. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Simkl.API.SimklApi.Post[T1,T2](String url, String userToken, T2 data)
   at Jellyfin.Plugin.Simkl.API.SimklApi.GetFromFile(String filename)
   at Jellyfin.Plugin.Simkl.API.SimklApi.GetHistoryFromFileName(BaseItemDto item, Boolean fullpath)
   at Jellyfin.Plugin.Simkl.API.SimklApi.MarkAsWatched(BaseItemDto item, String userToken)
   at Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler.ScrobbleSession(PlaybackProgressEventArgs eventArgs)`

**Comment by dedeweb** [comment]
For information, scrobbling is wokring again... May an api outage with simkl?

**Comment by crobibero** [comment]
Seems likely. I will leave tbis issue open so I remember to make the error message better whenI have time

**Comment by zeroquinc** [comment]
Scrobbling also isn't working here. Got both the Trakt.tv and Simkl plugin.

In the logs I can find this:

```
[03:45:01] [INF] [37] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Trying to scrobble Bulma's Big Day (ebb7fba0-40d4-31d5-f653-8167c58d6c2c) for desileR (21d898c4-1d1e-4e09-8aca-f57893dcbc94) - /mnt/unionfs/Media/TV-Anime/Dragon Ball Z (1989) {imdb-tt0214341}/Dragon Ball Z (1989) - S02E21 - Bulmas Big Day [Bluray-1080p][AC3 2.0][x264]-ZER0.mkv on 268bbe86c5f0f5dc63056236a8f35470

[03:45:01] [INF] [37] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History

[03:45:01] [INF] [25] Jellyfin.Plugin.Simkl.API.SimklApi: Posting: {"File": "/mnt/unionfs/Media/TV-Anime/Dragon Ball Z (1989) {imdb-tt0214341}/Dragon Ball Z (1989) - S02E21 - Bulmas Big Day [Bluray-1080p][AC3 2.0][x264]-ZER0.mkv", "Part": null, "Hash": null, "$type": "SimklFile"}

[03:45:01] [INF] [25] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
```

But the episode won't get marked as watched on Simkl, but it does in Trakt.

**Comment by Phil57** [comment]
I also have an issue for Friends. Logs say everything is ok but episodes are not scobbled.
It's working fine for other shows.

```
[2023-04-11 21:07:35.850 +02:00] [INF] [17] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Trying to scrobble "The One with Rachel's Sister (1)" (58097997-0782-d356-e61e-291249fb1758) for "jellyfin" (525bc2ba-4f41-4afb-ac50-5b41dc39381a) - "/media/shows/Friends (1994) {tvdb-79168} [tvdbid-79168]/Season 6/Friends.S06E13.1080p.BluRay.x265-RARBG.mp4" on "13cea6e905699637ec36db2de1b5ef89"
[2023-04-11 21:07:35.850 +02:00] [INF] [17] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
[2023-04-11 21:07:35.917 +02:00] [DBG] [17] Jellyfin.Plugin.Simkl.API.SimklApi: Response: SyncHistoryResponse { Added: SyncHistoryResponseCount { Movies: 0, Shows: 0, Episodes: 0 }, NotFound: SyncHistoryNotFound { Movies: [], Shows: [], Episodes: [] } }
[2023-04-11 21:07:35.917 +02:00] [INF] [17] Jellyfin.Plugin.Simkl.API.SimklApi: Posting: SimklFile { File: "/media/torrents/done/shows/Friends (1994) {tvdb-79168} [tvdbid-79168]/Season 6/Friends.S06E13.1080p.BluRay.x265-RARBG.mp4", Part: null, Hash: null }
[2023-04-11 21:07:36.152 +02:00] [INF] [41] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
[2023-04-11 21:07:36.169 +02:00] [DBG] [41] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Scrobbled without errors
```

**Comment by ekleop** [comment]
this was fixed here #24 
you can update dll from there or wait till the push request will be merged
