### ISSUE TITLE
Some content failing to scrobble

### ISSUE THREAD

**Issue by JamsRepos** [jellyfin/jellyfin-plugin-simkl#24]
Seems like certain items work, others do not. 

```
[2023-10-23 17:56:58.236 +01:00] [INF] [62] Jellyfin.Plugin.Simkl.API.SimklApi: Posting: SimklFile { File: "/mnt/unionfs/movies/1080/Bird Box (2018)/Bird Box (2018) {imdb-tt2737304} [WEBRip-1080p][EAC3 Atmos 5.1][x264]-DEFLATE.mkv", Part: null, Hash: null }
[2023-10-23 17:56:58.265 +01:00] [ERR] [62] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Caught unknown exception while trying to scrobble
System.Text.Json.JsonException: The JSON value could not be converted to Jellyfin.Plugin.Simkl.API.Responses.SearchFileResponse. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Simkl.API.SimklApi.Post[T1,T2](String url, String userToken, T2 data)
   at Jellyfin.Plugin.Simkl.API.SimklApi.GetFromFile(String filename)
   at Jellyfin.Plugin.Simkl.API.SimklApi.GetHistoryFromFileName(BaseItemDto item, Boolean fullpath)
   at Jellyfin.Plugin.Simkl.API.SimklApi.MarkAsWatched(BaseItemDto item, String userToken)
   at Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler.ScrobbleSession(PlaybackProgressEventArgs eventArgs)
```

**Comment by JamsRepos** [comment]
> look like the problem is with "File" key variable instead of "file" made some server side changes. Can you check?

```
[2023-10-23 22:35:11.257 +01:00] [INF] [63] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Trying to scrobble "1893" (f8637ceb-54d0-a591-01bd-a5908a5b2630) for "Jam" (26332453-a071-4748-af30-35301c8702d9) - "/mnt/unionfs/tv/1080/Loki (2021)/Season 02/Loki (2021) - S02E03 - TBA [DSNP WEBDL-1080p][EAC3 Atmos 5.1][h264]-FLUX.mkv" on "30b15cfe60706d57356c195f29bdec6b"
[2023-10-23 22:35:11.257 +01:00] [INF] [63] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
[2023-10-23 22:35:11.434 +01:00] [INF] [67] Jellyfin.Plugin.Simkl.API.SimklApi: Posting: SimklFile { File: "/mnt/unionfs/tv/1080/Loki (2021)/Season 02/Loki (2021) - S02E03 - TBA [DSNP WEBDL-1080p][EAC3 Atmos 5.1][h264]-FLUX.mkv", Part: null, Hash: null }
[2023-10-23 22:35:11.683 +01:00] [INF] [67] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
[2023-10-23 22:35:11.739 +01:00] [INF] [36] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2023-10-23 22:35:11.825 +01:00] [INF] [36] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Data Sync: User "Jam" ("26332453a0714748af3035301c8702d9") posted 2 updates
```
Does anything need to change/restart at all?

**Comment by JamsRepos** [comment]
@ekleop

```
[2023-10-23 23:46:15.835 +01:00] [INF] [26] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Trying to scrobble "Bird Box" (7e318795-f7ed-4ce0-42f0-c5bcbe48699e) for "Jam" (26332453-a071-4748-af30-35301c8702d9) - "/mnt/unionfs/movies/1080/Bird Box (2018)/Bird Box (2018) {imdb-tt2737304} [WEBRip-1080p][EAC3 5.1][x264]-BRiNK.mkv" on "30b15cfe60706d57356c195f29bdec6b"
[2023-10-23 23:46:15.838 +01:00] [INF] [26] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
[2023-10-23 23:46:16.014 +01:00] [INF] [33] Jellyfin.Plugin.Simkl.API.SimklApi: Posting: SimklFile { File: "/mnt/unionfs/movies/1080/Bird Box (2018)/Bird Box (2018) {imdb-tt2737304} [WEBRip-1080p][EAC3 5.1][x264]-BRiNK.mkv", Part: null, Hash: null }
[2023-10-23 23:46:16.058 +01:00] [ERR] [36] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Caught unknown exception while trying to scrobble
System.Text.Json.JsonException: The JSON value could not be converted to Jellyfin.Plugin.Simkl.API.Responses.SearchFileResponse. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Simkl.API.SimklApi.Post[T1,T2](String url, String userToken, T2 data)
   at Jellyfin.Plugin.Simkl.API.SimklApi.GetFromFile(String filename)
   at Jellyfin.Plugin.Simkl.API.SimklApi.GetHistoryFromFileName(BaseItemDto item, Boolean fullpath)
   at Jellyfin.Plugin.Simkl.API.SimklApi.MarkAsWatched(BaseItemDto item, String userToken)
   at Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler.ScrobbleSession(PlaybackProgressEventArgs eventArgs)
[2023-10-23 23:46:24.812 +01:00] [INF] [10] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "TW96aWxsYS81LjAgKE1hY2ludG9zaDsgSW50ZWwgTWFjIE9TIFggMTAuMTU7IHJ2OjEwOS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzExNy4wfDE2OTU4NjMwOTYyNTM1-26332453a0714748af3035301c8702d9-7e318795f7ed4ce042f0c5bcbe48699e"```

**Comment by ekleop** [comment]
maybe it's a normal behavior for this plugin when the movie wasn't detected(was detected as episode by the filename).
Because the API returns an empty [] for the Bird Box item. So if it's  still working after this error(Loki was detected ok for example) it can be skipped.

**Comment by JamsRepos** [comment]
> maybe it's a normal behavior for this plugin when the movie wasn't detected(was detected as episode by the filename). Because the API returns an empty [] for the Bird Box item. So if it's still working after this error(Loki was detected ok for example) it can be skipped.
> 
> And as I can see it's the same error as this #20 , this plugin tries to detect the movie\tv etc. only by name. Without any additional information. So it's not always possible.

It doesn't look like it's working though, Bird Box didn't update and nor is Loki which was the original file I mentioned in Discord. 

```
[2023-10-24 00:23:30.298 +01:00] [INF] [54] Jellyfin.Plugin.Simkl.API.SimklApi: Posting: SimklFile { File: "/mnt/unionfs/tv/1080/Loki (2021)/Season 02/Loki (2021) - S02E03 - TBA [DSNP WEBDL-1080p][EAC3 Atmos 5.1][h264]-FLUX.mkv", Part: null, Hash: null }
[2023-10-24 00:23:30.514 +01:00] [ERR] [54] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Items/970c1b325d58ff4b4548d0618faf7a17/playbackinfo".
System.ArgumentNullException: Value cannot be null. (Parameter 'item')
   at Emby.Server.Implementations.Library.MediaSourceManager.GetStaticMediaSources(BaseItem item, Boolean enablePathSubstitution, User user)
   at Emby.Server.Implementations.Library.MediaSourceManager.GetPlaybackMediaSources(BaseItem item, User user, Boolean allowMediaProbe, Boolean enablePathSubstitution, CancellationToken cancellationToken)
   at Jellyfin.Api.Helpers.MediaInfoHelper.GetPlaybackInfo(Guid id, Nullable`1 userId, String mediaSourceId, String liveStreamId)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPlaybackInfo(Guid itemId, Guid userId)
   at lambda_method371(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-10-24 00:23:30.550 +01:00] [INF] [54] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
```

**Comment by ekleop** [comment]
so nothing works after this error?  even the items that were scrobbled fine before, cannot be scrobbled?

**Comment by JamsRepos** [comment]
> so nothing works after this error?  even the items that were scrobbled fine before, cannot be scrobbled?

None of the items I've shown today have scrobbled once. I have other items scrobbling just fine on my profile. I've watched multiple episodes which have gone through and a couple movies.

**Comment by ekleop** [comment]
could you uncheck some of those items on simkl, then get this error with Blue Bird
and then try to scrobble good item you have uncheck?
try to understand if this error has any impact on next scrobbles.

**Comment by JamsRepos** [comment]
Blue Bird?

**Comment by ekleop** [comment]
sorry, Bird Box

**Comment by JamsRepos** [comment]
> could you uncheck some of those items on simkl, then get this error with Blue Bird and then try to scrobble good item you have unchecked? try to understand if this error has any impact on next scrobbles.

It seems Bird Box had already been scrobbled on my profile before. However, after removing the initial watch state and dropping it off my Watchlist, it has now scrobbled. 

However, Loki S2E3 still does not scrobble. Could this be due to the new functionality that was added to log multiple scrobbles of watched content?

```
[2023-10-24 09:30:59.696 +01:00] [INF] [51] Jellyfin.Plugin.Simkl.Services.PlaybackScrobbler: Trying to scrobble "1893" (f8637ceb-54d0-a591-01bd-a5908a5b2630) for "Jam" (26332453-a071-4748-af30-35301c8702d9) - "/mnt/unionfs/tv/1080/Loki (2021)/Season 02/Loki (2021) - S02E03 - TBA [DSNP WEBDL-1080p][EAC3 Atmos 5.1][h264]-FLUX.mkv" on "30b15cfe60706d57356c195f29bdec6b"
[2023-10-24 09:30:59.697 +01:00] [INF] [51] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
[2023-10-24 09:30:59.814 +01:00] [INF] [51] Jellyfin.Plugin.Simkl.API.SimklApi: Posting: SimklFile { File: "/mnt/unionfs/tv/1080/Loki (2021)/Season 02/Loki (2021) - S02E03 - TBA [DSNP WEBDL-1080p][EAC3 Atmos 5.1][h264]-FLUX.mkv", Part: null, Hash: null }
[2023-10-24 09:31:00.069 +01:00] [INF] [22] Jellyfin.Plugin.Simkl.API.SimklApi: Syncing History
```

Here's my profile, if you wish to see my watch states etc. https://simkl.com/5680253/

It seems this is the case too with Power, a show i've been watching these last few weeks. It seems Season 1 has scrobbled successfully however Season 2 and 3 which I have progress in have not scrobbled at all.

https://simkl.com/tv/46084/power

It seems only the first Season of a show scrobbles properly, then any other season does not.

**Comment by ekleop** [comment]
ok, let me do some investigations and improvements. Maybe will need a new push to github.

**Comment by JamsRepos** [comment]
> ok, let me do some investigations and improvements. Maybe will need a new push to github.

How's this going? Still noticing things not scrobbling properly.

**Comment by ekleop** [comment]
server side was updated yesterday, added support for imdb\tmdb etc. ids to the filename
what file wasn't scrobbled?
plugin is still in progress

**Comment by JamsRepos** [comment]
> server side was updated yesterday, added support for imdb\tmdb etc. ids to the filename what file wasn't scrobbled? plugin is still in progress

Power Season 3 Episode 3. I watched it about half an hour ago.

**Comment by ekleop** [comment]
need a full filename of the file you've watched.
You can get it from the jellyfish log(search by simkl) if you don't know

**Comment by JamsRepos** [comment]
> need a full filename of the file you've watched. You can get it from the jellyfish log(search by simkl) if you don't know

`Power (2014)/Season 03/Power (2014) - S03E02 - Its Never Over [NF WEBRip-1080p][AC3 5.1][x264]-NTb.mkv`

**Comment by ekleop** [comment]
thanks, will check.
Do you have metadata in the jellyfish for it? (poster, description etc... )

But significant increase in detection rate, will be only the plugin update(

**Comment by JamsRepos** [comment]
> thanks, will check. Do you have metadata in the jellyfish for it? (poster, description etc... )
> 
> But significant increase in detection rate, will be only the plugin update(

Full metadata yeah. It just seems to be for Seasons 2 and above. Season 1 of any show works fine, it's anything above that. Seemed to have happened since the Last Watched for VIP's was added (i'm a VIP, so maybe that could be a factor).

**Comment by ekleop** [comment]
ok, I hope, tomorrow will be some solution.

**Comment by JamsRepos** [comment]
> ok, I hope, tomorrow will be some solution.

Thanks for your ongoing help!

**Comment by ekleop** [comment]
made a lot of tests. So there's a way to scrobble by metada and not by filename only. It should work much better then. It's not fast by its in progress already. Hope, it will take few days or mb till the end of the week

**Comment by JamsRepos** [comment]
> made a lot of tests. So there's a way to scrobble by metada and not by filename only. It should work much better then. It's not fast by its in progress already. Hope, it will take few days or mb till the end of the week

No worries at all, thanks for the update. Let me know if you need me to test anything at all, glad the issue has got a solution.

**Comment by ekleop** [comment]
here, fixed all found bugs + detection rate should be much higher
https://github.com/ekleop/jellyfin-plugin-simkl/releases/tag/v3.1
after the test I'll make a push request to this repo.

**Comment by JamsRepos** [comment]
> here, fixed all found bugs + detection rate should be much higher https://github.com/ekleop/jellyfin-plugin-simkl/releases/tag/v3.1 after the test I'll make a push request to this repo.

Awesome, thanks so much! I should be able to replace this plugin with yours right?

**Comment by ekleop** [comment]
yes. Just replace with the new one and should be ok.

**Comment by JamsRepos** [comment]
> yes. Just replace with the new one and should be ok.

Can confirm, the ones I have reported are now scrolling properly. Thanks for getting this fixed!

**Comment by ekleop** [comment]
thanks, made a pull request. Will see if someone is still there

**Comment by Phil57** [comment]
Thanks a lot @ekleop, I had a show that wouldn't scrobbel at all which works now !

**Comment by ekleop** [comment]
the fix was pushed to realease. @crobibero the issue can be closed
